### ISSUE TITLE
Write a library for random number generation in order to be used for crypto-critical stuff.

### ISSUE THREAD

**Issue by danielinux** [tass-belgium/picotcp-modules#2]

**Comment by danielinux** [comment]
@alexlawriewood 
Comments:

1- there are a few warnings here and there. Please fix.
2- Some void function prototypes look like `something function()` instead of `something function(void)`. This is not accepted, please fix.

**Comment by alexlawriewood** [comment]
Okay, will sort.

A

________________________________
Van: Daniele Lacamera [notifications@github.com]
Verzonden: donderdag 5 februari 2015 14:05
Aan: tass-belgium/picotcp-modules
CC: WOOD Alexander
Onderwerp: Re: [picotcp-modules] Write a library for random number generation in order to be used for crypto-critical stuff. (#2)


@alexlawriewood<https://github.com/alexlawriewood>
Comments:

1- there are a few warnings here and there. Please fix.
2- Some void function prototypes look like something function() instead of something function(void). This is not accepted, please fix.

**Comment by danielinux** [comment]
Hey @alexlawriewood - 
libfortuna is about to get into production, and I can't still close this until you enable -Wall in your makefile, fix the warnings, and explicit (void) in the functions prototypes/definitions.

Any idea on the timing for this?

**Comment by alexlawriewood** [comment]
Ciao,

Do I have until next week sometime? Had planned to fix this weekend, but forgot my sister was visiting...

A
________________________________
Van: Daniele Lacamera [notifications@github.com]
Verzonden: vrijdag 13 februari 2015 15:01
Aan: tass-belgium/picotcp-modules
CC: WOOD Alexander
Onderwerp: Re: [picotcp-modules] Write a library for random number generation in order to be used for crypto-critical stuff. (#2)


Hey @alexlawriewood<https://github.com/alexlawriewood> -
libfortuna is about to get into production, and I can't still close this until you enable -Wall in your makefile, fix the warnings, and explicit (void) in the functions prototypes/definitions.

Any idea on the timing for this?

**Comment by danielinux** [comment]
@alexlawriewood ping?

**Comment by danielinux** [comment]
Looks fine, thanks.
Closed in e626ec5b43c2a9d81f81fcf5e404be7bb9522212
